FROM python:3.6
ENV PYTHONUNBUFFERED 1
ENV REDIS_HOST 'redis'
ENV REDIS_PORT 6379
RUN mkdir /code
WORKDIR /code
ADD requirements-wsserver.txt /code/
RUN pip install -r requirements-wsserver.txt
ADD . /code/
CMD ["python", "wsserver.py"]
