FROM python:3.6
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP "/code/ingestion_api.py"
RUN mkdir /code
WORKDIR /code
ADD requirements-ingestion.txt /code/
RUN pip install -r requirements-ingestion.txt
ADD . /code/
CMD ["flask", "run", "--host", "0.0.0.0"]
